### ISSUE TITLE
Upgrade Component for K8up 2.0

### ISSUE THREAD

**Issue by tobru** [projectsyn/component-backup-k8up#51]
## Context

K8up 2.0 contains breaking changes. Adapt the component to support K8up 2.0 and provide an upgrade path.

* https://k8up.io/k8up/explanations/what-has-changed-in-v2.html

## Alternatives

None

**Comment by simu** [comment]
Discussion during backlog refinement: To provide an upgrade path where users have a period of time in which they can migrate their backups from v1.x to v2.0, we came up with the idea to run K8up 1.x and K8up 2.0 side-by-side for a couple weeks which should be possible without big issues since the CRDs are different for 1.x and 2.0.

This would mean that the component needs to be able to deploy K8up 1.x and 2.0 on a single cluster and needs to be able to produce both the K8up 1.x and K8up 2.0 custom resources in the component library.
